
require "prototypes.terrain"
require "prototypes.decoratives"
require "prototypes.resources"
require "prototypes.planet"
require "prototypes.music"
require "prototypes.technology"
require "prototypes.items"
require "prototypes.recipes"
require "prototypes.machines"